# Site settings
title: Official arkwrn_ Blog
description: "An Official Blog of ARKWRN_"
baseurl: ""
url: ""

# User settings
username: arkwrn
user_title: ARKWRN_ - Blog's
email: hubungi.aja@gmail.com
twitter_username: arkwrn_
github_username:  Lidilidian
gplus_username:  108396188076217812919
disqus_username: arkwrn
profile_picture: https://scontent-sit4-1.cdninstagram.com/t51.2885-19/s150x150/20393609_319860788461851_1508877974508666880_a.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
timezone:      Asia/Jakarta

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
    
# projects in header index
projects:
  - name: Ceksipo
    url: https://github.com/arkwrn/ceksipo
  - name: Raw GeoJSON of Pahawang island
    url: https://github.com/arkwrn/Pahawang-Island-Data
  - name: MDC E-Library
    url: hhttps://github.com/arkwrn/E-Library
    
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

gems:
  - jekyll-seo-tag
